spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todoapp
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000

  mvc:
    static-path-pattern: /uploads/**
  resources:
    static-locations: file:./uploads/

app:
  upload-dir: ./uploads
